version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: video_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: video_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: video_api
    depends_on:
      - db
#    environment:
#      DATABASE_URL: postgresql://postgres:postgres@db:5432/video_db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "sleep 20 && 
             alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data: